# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: Run tests and linter for /unit-tests CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    defaults:
      run:
        working-directory: ./unit-tests

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}        
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: '**/package-lock.json'
      - name: CI
        working-directory: ./unit-tests
        run: npm ci
      - name: Build
        working-directory: ./unit-tests
        run: npm run build --if-present
      - name: Run Tests
        working-directory: ./unit-tests
        run: npm run test
      - name: Run Linter
        working-directory: ./unit-tests
        run: npm run lint:validation"
